### ISSUE TITLE
[bug] Livekit's CPU usage

### ISSUE THREAD

**Issue by furkanKotic** [livekit/client-sdk-flutter#364]
**Describe the bug**
When I test my application on Flutter iPhone, livekit's CPU usage is as follows: 

**Viewer CPU usage when there is a streamer in the room and his cameras are off:**
![1](https://github.com/livekit/client-sdk-flutter/assets/92918781/9159c9d6-a9c3-4ca7-afb8-1661bee6da6d)

**Viewer CPU usage when there is a streamer in the room and his cameras are on:**
![2](https://github.com/livekit/client-sdk-flutter/assets/92918781/69607402-7500-465f-a803-af56017f5edc)

**Viewer CPU usage when there are two streamers in the room and their cameras are on:**
![3](https://github.com/livekit/client-sdk-flutter/assets/92918781/5a734d5b-a3ac-4323-b363-6832e1d678d5)
![4](https://github.com/livekit/client-sdk-flutter/assets/92918781/73e53a76-6958-436d-b7ec-3182a17a222a)

**Viewer CPU usage when there are three streamers in the room and their cameras are off:**
![5](https://github.com/livekit/client-sdk-flutter/assets/92918781/b8e2b7a1-bb4e-461a-be07-16e6c40f76f7)

**Viewer CPU usage when two streamers in the room with their cameras on and one streamer with his camera off:**
![6](https://github.com/livekit/client-sdk-flutter/assets/92918781/eb806c00-dbd7-489e-99e7-4247d96fcfe7)

**When I test without a livekit connection in the same application, I observe 6% CPU usage.** 
In this case, we observe 50-60% CPU usage per broadcaster in Livekit. These processor uses cause the phone to overheat and increase battery usage.
I think Livekit needs optimization.

**Platform information**

* **Flutter version**: Flutter 3.13.4
* **Plugin version**: livekit_client: 1.3.5
* **Flutter target OS**: iOS

**Comment by Parfyonator** [comment]
Hi. Users of my app that has video call integrated by means of this plugin also experience overheating. For some of them it is moderate and for the others it is pretty high.

**Comment by cloudwebrtc** [comment]
hey @furkanKotic @Parfyonator, Hey, can you guys confirm what video code was being used when this issue occurred, and what phone model you were using? I think the video code that consumes the most power in libwebrtc is usually the video code.

**Comment by furkanKotic** [comment]
Hi @cloudwebrtc. The scenario of @Parfyonator is also valid for me. My users report that the phone overheats after 30 minutes, the app becomes extremely slow, and the phone gives a high temperature warning. We are using H264 codec. We know that it is available in all recent iPhone models. 

**Some tested models:**
iPhone 15 pro max
iPhone 14 pro max
iPhone 14
iPhone X

I have all of these devices. These devices experience overheating when broadcasting or just participating as a viewer. But there is no problem on Android devices.

Resolution: h540_43
Bitrate: 1000
Framerate: 15

**Comment by dragontran** [comment]
Heyo! I wanted to point out that I've observed high CPU usage and high temps during extended use in my project, the LiveKit example project, and the Flutter WebRTC example project. I tested these projects on my iPhone XR, using the H264 encoder at a 540_43 resolution and 20 fps.

I also experimented with the example project for the camera package. It appears to utilize approximately 30% CPU when the camera is active. Is it typical for the camera in Flutter for iOS to demand such high CPU consumption?

Also, a big thanks for everything you do. @cloudwebrtc

**Comment by EqualCHZH** [comment]
I have the same heating problem. iPhone users complain about the application overheating and overheating after 30 minutes of use.

@cloudwebrtc @davidzhao

**Comment by domvie** [comment]
Can confirm, same thing happens to our iOS devices (12, 14 Pro, iPad Pro 11"). Very high energy + CPU usage. Perhaps this is a flutter-webrtc issue?

**Comment by elonmaph** [comment]
high cpu ,high energy and high temperature, Is there any official plan to solve this performance problem?

**Comment by cloudwebrtc** [comment]
Hey all, we will investigate this issue this week. Can you post the model and year of the device you are using?

**Comment by cloudwebrtc** [comment]
> Can confirm, same thing happens to our iOS devices (12, 14 Pro, iPad Pro 11"). Very high energy + CPU usage. Perhaps this is a flutter-webrtc issue?

Could you provide some reference for cpu usage?
For example, open the camera on 14 pro, or publish a 720p video track using h264,
I have a 14 pro, and iPad air M1, I will do a comparison test

**Comment by domvie** [comment]
> > Can confirm, same thing happens to our iOS devices (12, 14 Pro, iPad Pro 11"). Very high energy + CPU usage. Perhaps this is a flutter-webrtc issue?
> 
> hi @domvie Could you provide some reference for cpu usage? For example, open the camera on 14 pro, publish a 720p video track with using h264, I have a 14 pro, and iPad air M1, I will do a comparison test

So I just re-tested this using the livekit client-sdk-flutter example (I believe its version 2.1.0) as of right now. I connected with two real clients (iPhone 12, iPad Pro 11"). At times I've played around with adding a couple of video publishers using livekit-cli but that never seemed to make a difference.

Some stats I'm getting:

- H264/720p/30fps/Simulcast/Adaptive Stream/Dynacast after ~10min:
iPhone 12: CPU ~50%, Energy Impact: "Very High" (with GPU taking around ~45% and "Overhead" the next largest 25%). **No overheating**.
iPad: Virtually the same stats, also no overheating
  

- Same settings as above but with E2EE:
Again pretty much same as above, except CPU spikes to around ~60%, no overheating. 

- Same settings as above but 1080p and simulcast off:
No difference, no overheating.

- Everything off, 1080p/30fps (and I assume still h264 by default?):
Again all the same and no overheating.

- VP8, 1080p/30fps, everything enabled again:
iPhone 12: CPU goes up to around 130%
iPad: CPU ~65%
quite expected. The devices, especially iPhone, do get noticeably warmer this time. Not so much that I get a OS warning about it though (which honestly was the biggest issue, even worse than the extreme throttling that would happen sometimes), but it's very warm.

- AV1, 1080p/30fps, again everything enabled:
CPU goes up substantially, to around 200-300% especially when moving camera. Still warm/hot, some throttling, but not yet overheating.


At this point I have stopped testing as it is quite time consuming. 

All in all, in this session I could unfortunately not reproduce the overheating issue I encountered a while back. Especially when using hardware accelerated H264 the devices seemed to run just fine, other codecs increased CPU and heat quite a bit (although that is to be expected). Energy consumption was always very high.

I'm guessing this could be due to multiple reasons:
- not testing long enough with various settings/combinations
- perhaps the problem lies somewhere in the implementation of livekit in our app, or some UI/Flutter component triggering it
- different version? (was tested on v2.0 before)

In the current form of our app it also does not overheat most of the time. We enable only dynacast, everything else off, with a resolution of 1440p @ 30fps and max bitrate of 15mbps using H264. These are the settings we had the most success with for our requirements. So it can definitely handle quite a bit of data without causing issues. I also remember the problem happening independent of res/fps, so it would also overheat at say 540p and a low frame rate. The weirdest thing to me is that it's not easily reproducible, or why it would sometimes happen with h264 and sometimes not. Other codecs make more sense I guess but even then it was never obvious.

Hopefully this was somehow helpful, sorry I couldn't reproduce it this time. Perhaps @furkanKotic still can.

**Comment by elonmaph** [comment]
should I just upgrade the sdk to 2.1.5 to solve this issue?

**Comment by cloudwebrtc** [comment]
@elonmaph  you can try this branch https://github.com/livekit/client-sdk-flutter/pull/509, and change `VideoTrackRenderer` like this.

```dart
VideoTrackRenderer(
    _videoTrack!,
    fit: RTCVideoViewObjectFit.RTCVideoViewObjectFitContain,
    renderMode: VideoRenderMode.platformView,
  )
```

**Comment by dragontran** [comment]
I've been testing the platform view branch and wanted to share some feedback. The CPU performance improvements are definitely noticeable and my iphone hasn’t overheated, which is fantastic! 

However, I’ve encountered a couple of issues:
- The platform views do not respect the RTCVideoViewObjectFit.RTCVideoViewObjectFitCover fit option and extend beyond the widget frame.
- The video feed briefly freezes when muting/unmuting the microphone. This issue worsens when rapidly toggling mute/unmute.

I’m really excited about the platform view and performance updates for iOS! Thanks so much for your help!

**Comment by furkanKotic** [comment]
> * The platform views do not respect the RTCVideoViewObjectFit.RTCVideoViewObjectFitCover fit option and extend beyond the widget frame.

I noticed this problem too. It's like it doesn't care about the height of the Sizedbox and the image is created with a size higher than the value given to the Sizedbox.
