### ISSUE TITLE
Web: Flickering with example app 

### ISSUE THREAD

**Issue by hiroshihorie** [livekit/client-sdk-flutter#5]
When connected to a room, video seems occasionally to flicker. Might be related to Flutter's state management.

**Comment by hiroshihorie** [comment]
Might be related to Flutter's state management.

**Comment by The-Funk** [comment]
I have this same issue with a modified version of the sample code and I have determined that it comes from the listener function attached to the Room object. When the room object changes the _onRoomDidUpdate function fires and setState is called. This causes the page to rerender which is where your flickering is coming from.

I also believe that this is being caused (in my case) by audio changes. Fire up the camera in a mostly silent environment, make no noise, the flicker doesn't seem to occur. Now make a few very loud noises. The livekit server detects this and returns information via the websocket indicative of who in the room is the "speaker" based on mic values.

I'm not sure how to best fix this because I'm still learning flutter state management. On one hand you want the room object up to date, and being as it is a piece of state, that means calling setstate, but on the other hand, rerendering the entire video on every room change seems a tad wasteful. So my initial thought is you'd want to avoid rerendering the video and only rerender the portion of the page that needs to know about mic level changes, such as a different widget (in a stack or overlay) with, for instance, a speaker icon.

**Comment by alex-bluetrain** [comment]
I just answered this on slack, so I paste the comment here for reference:

The flickering happens when the RTCVideoRenderer is rebuilt on UI updates. To avoid that what I do is to set autoSubscribe to false in connect(), because autoSubscribed tracks don't trigger a "TrackSubscribedEvent". 

Instead: after joining the room I iterate over each participant's video trackPublication and set the publication.subscribed=true. That indeed triggers the TrackSubscribedEvent.

And now you can create and initialize the RTCVideoRenderer on TrackSubscribedEvent and dispose it on TrackUnsubscribedEvent. 

no more flickering that way. I've tried it on flutter (iOS, Web & Android) it works perfectly

**Comment by The-Funk** [comment]
I can verify that alex-bluetrain's fix works and that this isn't so much an issue with the sdk itself as it is a state management issue. The flickering is caused by reinitializing the renderer at improper times.

**Comment by hiroshihorie** [comment]
Thanks guys for the clues I will look into this, I think it is related to `flutter_webrtc` package that the SDK depends on.

**Comment by hiroshihorie** [comment]
Thanks guys for the clues I will look into this, I think it is related to `flutter_webrtc` package that the SDK depends on.

**Comment by hiroshihorie** [comment]
I re-checked now and can't seem to reproduce it.
It might got fixed unintentionally when I implemented this PR https://github.com/livekit/client-sdk-flutter/commit/16910cae25ba63aaeb1cf42a33a3b5d67ca93f0c
VideoTrackRenderer doesn't use ChangeNotifier anymore, it uses Events.
This will be in a new release.

**Comment by postacik** [comment]
I pulled the `main` branch and made a test with the example app on Chrome. The flickering I saw before seems to have gone.

**Comment by docisit** [comment]
I have this issue in my app, with self hosted livekit. using ingress whip, when my guest is in the room and the guest talks, it causes the guest video to flicker. And, this only happens on the guest device. Not on the video track in the room for others, or in my obs studio.  I believe it is the AEC.  Trying to track down the cause now.

**Comment by docisit** [comment]
> I can verify that alex-bluetrain's fix works and that this isn't so much an issue with the sdk itself as it is a state management issue. The flickering is caused by reinitializing the renderer at improper times.

   Definitely great advice, and I am making changes now. I have just spent 2 days trying to fix the flicker, on guest device, and I believe this is the fix.

**Comment by docisit** [comment]
You guys got it! Thanks for the great software and the above helped me fix the flicker. It was only in guest device, and I got it! You guys know how great a feeling it is to test, and all works lovely! Just did, and it’s golden.  I’m using my app to let coaches and athletes sign in, and join my show, by pulling them into OBS studio via browser source, and mix them with me and pushing the Ingress back
