### ISSUE TITLE
[bug] No Reconnected Event after AttemptReconnect

### ISSUE THREAD

**Issue by holzgeist** [livekit/client-sdk-flutter#500]
**Describe the bug**

I try to give users feedback about connectivity issues as fast as possible, i.e. on RoomAttemptReconnectEvent. However, it looks like "RoomReconnectedEvent" is not always fired after attempting to reconnect and the UI is stuck in the "reconnect" screen/indicator

**To Reproduce**

* listen to RoomAttemptReconnectEvent and RoomReconnectedEvent
* tamper with connectivity (wifi on/off, mobile data on/off etc)
* see good connectivity even without reconnected event

**Expected behavior**

Reconnected events are always fired after attempting to reconnect.

**Platform information**
* **Flutter version**: 3.19.5
* **Plugin version**: 2.1.2
* **Flutter target OS**: Android, real device
* **Flutter target OS version**: 13

**Comment by padi-dev-anhntn** [comment]
i'm too

**Comment by padi-dev-anhntn** [comment]
@holzgeist

**Comment by pitazzo** [comment]
Hi @cloudwebrtc,

In our use case, it’s important for us to leave the room automatically when the other participant does. If this happens during a connection recovery, we’ve noticed that the `ParticipantDisconnectedEvent` may be lost, which means the other participant wouldn’t leave.

Based on this, we’re considering a strategy where we check the number of remote participants after reconnection, and if it equals zero, we leave. However, since you mentioned that the `RoomReconnectedEvent` is only emitted after a full reconnection, which event would you recommend for checking the number of remote participants?
