### ISSUE TITLE
[bug] Can't change audio device on Android

### ISSUE THREAD

**Issue by MarcusHellkvist** [livekit/client-sdk-flutter#567]
**Describe the bug**
Can't change audio device on Android.

**To Reproduce**
1. clone example app from [https://github.com/livekit/client-sdk-flutter](url) 
2. start on android
3. connect to room
4. change audio device using dropdown in example app

**Expected behavior**
Audio device should change to the selected one.

**Platform information**

* **Flutter version**:  3.22.2
* **Plugin version**: 2.2.3
* **Flutter target OS**:  Android
* **Flutter target OS version**: 14
* **Flutter console log**:  n/a

**Additional information**
edit: everything seems to be working fine with livekit_client: 2.1.5

**Comment by cloudwebrtc** [comment]
Since mobile devices manage output differently than desktops, trying to change the output device can lead to all sorts of confusing states. For example, if you switch the output from the built-in speaker to Bluetooth or wired headphones, the input will also change, so we removed support for setting output devices in this commit. Therefore, Android/iOS only has two states, speaker mode, or other default output. When using the default output, the system takes over the output order. For example, if you plug in a wired headset, it will switch to the wired headset, and if you unplug it, it will automatically revert to the handset (if setSpeakerPhone(false)). The same goes for Bluetooth headphones.

https://github.com/livekit/client-sdk-flutter/commit/a734d6d4123edef4e299cbbf2ebdf0ebe3c7861f#diff-821dcb55617b94092d660e27084e75e60bd45fc4f8562327f585142679aa1393L107-L112

**Comment by cloudwebrtc** [comment]
Normally when setSpeakerPhone(true), the default sound will be sent to the Speaker output, but if a Bluetooth headset or wired connection is connected, the sound will automatically be output from the newly connected device.

The difference of setSpeakerPhone(false) is that the default device is the handset, and the result will be the same as above after connecting a new device.

I think this is the way that meets the user's intuition.
