### ISSUE TITLE
microphone not published on windows build

### ISSUE THREAD

**Issue by alex-bluetrain** [livekit/client-sdk-flutter#64]
When building or running on windows, the localAudioTrack (microphone) doesn't get published.

it doesn't show any errors or warnings, it just doesn't work.

I've tried with LocalAudioTrack.create() + localParticipant.publishAudioTrack()
and also with just the localParticipant.setMicrophoneEnabled(true);

same results.

to reproduce: just run or build the example provided in client-sdk-flutter and check the published audio tracks on the room.

tested on 0.5.5

**Comment by jdde** [comment]
Hey @alex-bluetrain does the client-sdk-flutter already supports windows?
Based on the README.md in the master branch, it's not yet supported. (Work in progress)

**Comment by cloudwebrtc** [comment]
I'm pretty sure that this bug is caused by the `built-in AEC` startup logic because some users in `dart-sip-ua` reported similar issues. when playback is started before recording, and Windows has `built-in  AEC` enabled, the microphone will fail to start. 

The PR of the relevant native SDK, then the `flutter-webrtc` needs to be updated.
https://github.com/webrtc-sdk/webrtc/pull/23

**Comment by cloudwebrtc** [comment]
fixed https://github.com/livekit/client-sdk-flutter/pull/127
