### ISSUE TITLE
[bug]There is a problem with setting the output device when connecting a Bluetooth headset

### ISSUE THREAD

**Issue by lurongshuang** [livekit/client-sdk-flutter#643]
**Describe the bug**
When a Bluetooth headset is connected, the audioOutputs queried by the Android side will have:
0 = MediaDevice{deviceId: bluetooth, label: Free BYRD, kind: audiooutput, groupId: bluetooth}
1 = MediaDevice{deviceId: speaker, label: Speakerphone, kind: audiooutput, groupId: speaker}
2 =  MediaDevice{deviceId: earpiece, label: Earpiece, kind: audiooutput, groupId: earpiece}
use : _room.setAudioOutputDevice(device);
Set any device output, and the Bluetooth headset device will emit sound

**Describe the bug**
iOS phone cannot find the Receiver device，but can find it occasionally，
0 =  MediaDevice{deviceId: com.apple.avfoundation.avcapturedevice.built-in_video:0, label: Back Camera, kind: videoinput, groupId: nu
1 = {UNEEDMediaDevice} MediaDevice{deviceId: com.apple.avfoundation.avcapturedevice.built-in_video:1, label: Front Camera, kind: videoinput, groupId: n
2 = MediaDevice{deviceId: Built-In Microphone, label: iPhone 麦克风, kind: audioinput, groupId: MicrophoneBuiltIn}
3 = MediaDevice{deviceId: Speaker, label: 扬声器, kind: audiooutput, groupId: Speaker}

**Describe the bug**
At the same time, after the iOS phone is connected to the headset, the headset device can be found for the first time. When it is switched to the speaker, the headset device will disappear and cannot be found. In addition, the Bluetooth connection device is in the connected state in the phone settings.

Flutter (Channel stable, 3.24.3, on macOS 15.1.1 24B91 darwin-arm64, locale
    zh-Hans-CN)
android 14  galaxy S22+
iOS iPhone X
livekit_client: ^2.3.0

**Comment by cloudwebrtc** [comment]
Enumerating the device list on mobile devices is not reliable, because it works differently from desktop (Windows/macOS), there is a system audio routing management control, so on mobile devices not always can list all audio devices (sometimes not accurate), so the output can let the system take over, just set to use/or not use the `Hardware.instance.setPreferSpeakerOutput(bool)`.  and avoid using _room.setAudioOutputDevice(device); for mobile
